task_type: multilabel_classification

loss:
  _target_: torch.nn.BCEWithLogitsLoss

metrics:
  auroc:
    _target_: torchmetrics.AUROC
    task: multilabel
    num_labels: ${dataset.num_classes}
  auprc:
    _target_: torchmetrics.AveragePrecision
    task: multilabel
    num_labels: ${dataset.num_classes}
  f1score:
    _target_: torchmetrics.F1Score
    task: multilabel
    num_labels: ${dataset.num_classes}