defaults:
  - _self_
  - dataset: ???
  - model: ???

train:
  dataset: 
    split: scaffold_split
    split_sizes: [0.8, 0.1, 0.1]
    num_node_features: ???
    num_edge_features: ???
  batch_size: 32
  epochs: 100
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0005