# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/job_logging: custom

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    direction: minimize
    study_name: CMPNN
    n_trials: 10
    n_jobs: 1
    params: 
      model.communicator_name: choice("additive", "inner_product", "gru", "mlp") 
      model.num_conv_layers: range(2, 4, step=1)
      model.hidden_channels: choice(64, 128, 300)
      train.batch_size: choice(16, 32, 64)
