# @package _global_

defaults:
  - _self_
  - search_spaces@hydra.sweeper.params: ???
  - override /hydra/sweeper: optuna
  - override /hydra/job_logging: custom

# Optuna pruning is not supported with hydra (https://github.com/facebookresearch/hydra/issues/1954)
# Pruning requires sequential execution of trials and pruning decision is made based on past trials
# Currently the trials can be run in parallel (by setting n_jobs>1)
hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    direction: minimize
    study_name: ${model.model_cls}
    n_trials: 50
    n_jobs: 1 

train:
  trainer:
    logger:
      group: ${model.model_cls}-Optuna # i.e., CMPNN-Optuna
      name: null